### ISSUE TITLE
Login does not accept keyboard input without first moving mouse.

### ISSUE THREAD

**Issue by Restraint** [Antergos/lightdm-webkit2-greeter#96]
I cannot press Enter to login without first moving my mouse pointer into the screen where the greeter is located. I have 2 monitors and the greeter is on the left one, so I have to move my mouse to the left before the greeter starts accepting any type of keyboard input.

**Comment by lots0logs** [comment]
This should be fixed in the latest master branch. As soon as meson (build tool) releases 0.37 I'll release the next major version of the the greeter (code is currently on master branch).

**Comment by lots0logs** [comment]
@Restraint Could you let me know if the issue still occurs with the latest release?

**Comment by Restraint** [comment]
@lots0logs I still have the issue. Unless you mean the latest master branch version that I have to build? In which case I haven't tried that yet.

**Comment by lots0logs** [comment]
No, just the latest released package version. Hmm..what does your screen layout look like? Which one is primary and which one does the greeter show on?

**Comment by Restraint** [comment]
2 monitors. The greeter shows on the left one, which is also the primary. The right screen is just a black screen during login. Also, is there a way to ensure that I have to latest version beyond just sudo pacman -Syu lightdm-webkit2-greeter? Sorry if it's a dumb question, not too familiar with Linux in general.

**Comment by lots0logs** [comment]
Its weird that your mouse cursor doesn't start on the same display as the greeter. I'll look into it to see if there's anything that can be done. 

You can see which version you have installed with `pacman -Q lightdm-webkit2-greeter`. The latest release version is listed on the README for this repo.

**Comment by Restraint** [comment]
Well, the version matches, but if it matters at all, I'm pretty sure i had to use xrandr to set the left monitor as the primary one. The default configuration had the greeter displayed on the right monitor. Not sure if it matters because my mouse cursor seems to initialize in the middle of both screens.

**Comment by Draghi** [comment]
I'm currently having this issue as well.

I've got two 1080p screens, the one on the left runs at 144hz and is set as primary, while the one on the left runs at 60hz. 

The login screen appears on the primary monitor and the secondary monitor is black, but still on and allows the mouse to enter it. The mouse appears right in the middle of the two screens, resulting in it starting on the 0th pixel of the right-hand monitor. The mouse then needs to be moved onto the primary monitor before you're able to input anything.

This occurs on: 
- Startup
- Sleep 
- dm-tool lock

System Info:
- Package Version: 2.2.5-1
- Distro: Antergos (4.14.13-1-ARCH, x86_64)
- Driver: nvidia 387.34-19 (w/nvidia-settings generated X11 config)
- DE: XFCE + compton

However, my last system [Antergos, KDE, Nvidia Proprietary] behaved differently - which was up-to-date about a week ago now. Rather than leaving the secondary monitor on, it would turn it off and position the mouse in the centre (and ignore the primary monitor setting, but I've got a feeling that was something else).

**Comment by Rodancoci** [comment]
Hi! I'm experiencing this as well. Any news on a fix?
